// Interpreting C++(ICPP) - Run C++ anywhere, just like a script.
// Copyright (c) 2026 Jesse Liu <neoliu2011@gmail.com>
// SPDX-License-Identifier: Apache License, Version 2.0
// See LICENSE file in the root directory for full license text.

syntax = "proto3";

package com.vpand.imod;

message File {
  string path = 1; // relative to .icpp local repository root directory
  bytes content = 2; // file buffer
}

message MoudlePackage {
  uint32 version = 1; // imod version
  string name = 2; // module name 
  repeated File files = 3; // all the module files
}
